alter table coordinate_tbl add column devicetype text not null, add column name_X text,add column name_Y text,
    add column sex_X text,add column sex_Y text,
    add column age_X text,add column age_Y text,
    add column heigth_X text,add column height_Y text,
    add column testdate_X text,add column testdate_Y text,
    add column score_X text,add column score_Y text,
    add column body_age_X text,add column body_age_Y text,
    add column fat_X text,add column fat_Y text,
    add column fat_scale_X text,add column fat_scale_Y text,
    add column fat_range_X text,add column fat_range_Y text,
    add column bone_X text,add column bone_Y text,